language: ruby
cache: bundler
script:
- gem install bundler --no-ri --no-rdoc
- gem install execjs
- RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
  app: refiqi-monggovest
  on:
    repo: Refiqi/Monggovest
    branches:
      only:
        - master
        - develop
  run:
    - rake db:migrate
