language: ruby
cache: bundler
script:
- gem install bundler --no-ri --no-rdoc
- gem install execjs
- RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
deploy:
  provider: heroku
  api_key:
    secure: oO+SX433yrGzQWGlBkQRSM6KVVCzavgxBmKssWhKmVNUgTPehE2fU+RKN0KU02/wG0eDDhxRTdSp7Mp9O/2MMuatEJBeK+rnSHaw2m1Qg0BI+HBxueyvXxff9v9NxtUQ9PrUiP+vIXTgJ+V3LzKdE1q+acaiHA7iFoKA8S+1+EsojFgHyqyYOPbUjMdEeSIojr/A+KsXJZjppob+NFkIIzRJGrwYlTbMJ7RLjbfiGbyZ+ceQdHBgtHuazy3hQpLchyAt3EUxQRPvvBGgFke2vYy8CNDH6ThYHUdPla2+iVL9fRhj7plIacBzUESCnl3Eb91gboU4L114PeRN4n4CqOsFqgRZFHIZgjIfzcSFG+oeVe1Pn4RdqfmGJCdMwcpR+IRvmul82o6xSfoYG1u7rZyXWqWbdiJufoyZ/NnefA3kroWIsMRIRDcTexbAaC33C7pQlp+3bvGc21MmPhZGV/jM4Wo1sokJFhNcwPIdb8Z+L2Fp6FUncBfW2xQQv3jQ5Zd6qY9FlBUXCpJOsECXMNND9/DPRTnzeisU9eXirYOUgniw74SS3K8kZrzVHSGkwXidjkPYOEiugoTVDMhJHHkFQZnSSuw1PrblH2P+tVk9/g69dBrfC6pAnQzCJ2O9oJykltgl+WDj3oCxm34RphOqc9jxOMcRcRkI79grmpc=
  app: refiqi-monggovest
  on:
    repo: Refiqi/Monggovest
    branches:
      only:
        - master
        - develop
  run:
    - heroku run rake db:migrate
