# config cloudinary yml
development:
  cloud_name: monggovest
  api_key: '188276867988969'
  api_secret: BbwUVsbcjDPWsm1Lzq-QBJIXeaI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: monggovest
  api_key: '188276867988969'
  api_secret: BbwUVsbcjDPWsm1Lzq-QBJIXeaI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: monggovest
  api_key: '188276867988969'
  api_secret: BbwUVsbcjDPWsm1Lzq-QBJIXeaI
  enhance_image_tag: true
  static_image_support: false
